### ISSUE TITLE
Encontrar forma de automatizar por completo sincronização da Wiki

### ISSUE THREAD

**Issue by philipeatela** [natahouse/quality#3]
Atualmente é necessário executar um comando de push manual a partir de um repo local, para sincronizar as alterações para o repositorio .wiki

Precisamos encontrar uma maneira de automatizar isso, talvez pelo actions, para economizar tempo e facilitar o controle de qual conteúdo está disponível ou não. O ideal seria que depois do merge de qualquer PR, ele clonasse o repo e executasse um `git push` automaticamente.

**Comment by RaphaelOliveiraMoura** [comment]
Achei alguns exemplos que a gnt pode se basear

https://github.com/marketplace/actions/github-wiki-sync-action
https://github.com/marketplace/actions/publish-to-github-wiki
https://github.com/Microsoft/TypeScript-wiki/actions/runs/19388458/workflow
https://github.com/tedbrandston/wiki-test/blob/master/.github/workflows/sync-to-wiki.yml
