### ISSUE TITLE
Replace "master" with alternative term to avoid slavery references

### ISSUE THREAD

**Issue by HigorAlves** [natahouse/quality#9]
**What would you like to be added**:

Replace ```master``` branch with the new one ```main```

**Why is this needed**:

To avoid slavery references, to do this follow this steps:

**Update Local**

```bash
$ git branch -m master main
$ git push -u origin main
```

**Update Repo**

- Navigate to your repository > Settings > Branches
- Select main as your default branch
- Update your branch protection rules
- Navigate to Code > Branches and delete master

**Comment by philipeatela** [comment]
Done!
